name: Update readme ⭐️ progress

on:
    schedule:
        - cron: "11 */6 * * *" # Every 6 hours
    workflow_dispatch:

jobs:

    update-readme:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              env:
                  TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TEST_SECRET: ${{ secrets.TEST_SECRET }}
              run: |
                  echo ${#TEST_GITHUB_TOKEN}
                  echo ${#TEST_SECRET}
            - uses: actions/checkout@v2
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
            - uses: k2bd/advent-readme-stars@v1
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}
            - uses: stefanzweifel/git-auto-commit-action@v4
              if: ${{ env.AOC_ENABLED }}
              env:
                  AOC_ENABLED: ${{ secrets.AOC_ENABLED }}
              with:
                  commit_message: "update readme progess"
